
name: my-playwright-test

on:
  workflow_dispatch: 
   inputs:
     target_environments:
      description: Environment to test
      type: environment
      default: dev 
        
        
      required: true
jobs:
  test:
   runs-on: ubuntu-slim
   environment: 
   name: ${{inputs.target_environments}}
  
