
name: my-playwright-test

on:
  workflow_dispatch: 
   inputs:
     target_environments:
      description: Environment to test
      type: choice
      default: dev
      options:
        - dev
        - qa
        - stage
        - uat
        - prod
        
      required: true
jobs:
  test:
   runs-on: ubuntu-slim
   environment: 
   name: ${{inputs.target_environments}}
  
