name: Playwright Tests
on:
 workflow_dispatch:
env:
  DAY_OF_WEEK: Monday 
 run: |       
          # Use $ to print the environment variable values
          echo "The base URL is: $DAY_OF_WEEK"
          echo "The username is: $MY_NAME"
        
jobs:
  test:
    timeout-minutes: 60  
    env:
     MY_NAME: Anil
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-test-results
        path: test-results/
